version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio # Using the official MinIO image
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # MinIO Console port
    volumes:
      - minio_data:/data # Persistent storage for MinIO data
    environment:
      MINIO_ROOT_USER: minioadmin # Set your desired root username
      MINIO_ROOT_PASSWORD: minioadmin # Set your desired strong root password
      MINIO_SERVER_URL: http://127.0.0.1:9000 # Optional: Configure the server URL
    command: server --console-address ":9001" /data # Start MinIO server and console
    healthcheck: # Optional: Health check for the service
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # app:
  #   build: .
  #   depends_on:
  #     - rabbitmq
  #     - postgres
  #     - redis
  #   environment:
  #     RABBITMQ_HOST: rabbitmq
  #     RABBITMQ_PORT: 5672
  #     RABBITMQ_QUEUE: my_queue
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   ports:
  #     - "8000:8000"

  # postgres:
  #   image: postgres:14-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 20 1 --appendonly yes
  #   volumes:
  #     - redisdata:/data

volumes:
  mysql_data:
  minio_data:
  # pgdata:
  # redisdata:
