apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
data:
  #### MySQL
  mysql-root-password: dG9vcg== # "password" (base64 encode)
  mysql-user: dXNlcg==
  mysql-pass: cGFzc3dvcmQ=
  mysql-db-name: ZmhueA==
  #### RabbitMQ
  rabbitmq-user: Z3Vlc3Q=
  rabbitmq-pass: Z3Vlc3Q=
  #### Minio
  minio-access-key: bWluaW9hZG1pbg==
  minio-secret-key: bWluaW9hZG1pbg==

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  app-name: aW1wb3J0LXNlcnZpY2U=
